file_write = open('Codingal.txt', 'w')
file_write.write("File in write mode....")
file_write.write("Hi I'm Penguin. I'm one year old")
file_write.close()
file_append = open('Codingal.txt', 'a')
file_append.write("File in append mode....")
file_append.write("Hi I'm Penguin. I'm one year old")
file_append.close()
file_read = open('Codingal.txt','r')
print("File in Read Mode -")
print(file_read.read())
file_read.close()